<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CJMmeiOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cJMmeiO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cJMmeiO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'parent' => ['privates', '.errored..service_locator.cJMmeiO.App\\Entity\\Parents', NULL, 'Cannot autowire service ".service_locator.cJMmeiO": it references class "App\\Entity\\Parents" but no such service exists.'],
        ], [
            'parent' => 'App\\Entity\\Parents',
        ]);
    }
}
