<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TNLtUKRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tNLtUKR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tNLtUKR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'timeTableRepository' => ['privates', 'App\\Repository\\TimeTableRepository', 'getTimeTableRepositoryService', true],
        ], [
            'timeTableRepository' => 'App\\Repository\\TimeTableRepository',
        ]);
    }
}
