<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2h6NWmYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2h6NWmY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2h6NWmY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'marksRepository' => ['privates', 'App\\Repository\\MarksRepository', 'getMarksRepositoryService', true],
        ], [
            'marksRepository' => 'App\\Repository\\MarksRepository',
        ]);
    }
}
