<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ERbhixService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._ERbhix' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ERbhix'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mark' => ['privates', '.errored..service_locator._ERbhix.App\\Entity\\Marks', NULL, 'Cannot autowire service ".service_locator._ERbhix": it references class "App\\Entity\\Marks" but no such service exists.'],
        ], [
            'mark' => 'App\\Entity\\Marks',
        ]);
    }
}
