<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WioxKy0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wioxKy0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wioxKy0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'subject' => ['privates', '.errored..service_locator.wioxKy0.App\\Entity\\Subject', NULL, 'Cannot autowire service ".service_locator.wioxKy0": it references class "App\\Entity\\Subject" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'subject' => 'App\\Entity\\Subject',
        ]);
    }
}
