<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G1apj0gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G1apj0g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G1apj0g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'parent' => ['privates', '.errored..service_locator.G1apj0g.App\\Entity\\Parents', NULL, 'Cannot autowire service ".service_locator.G1apj0g": it references class "App\\Entity\\Parents" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'parent' => 'App\\Entity\\Parents',
        ]);
    }
}
