<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarksTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MarksType' shared autowired service.
     *
     * @return \App\Form\MarksType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MarksType.php';

        return $container->privates['App\\Form\\MarksType'] = new \App\Form\MarksType();
    }
}
