<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarks2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._ERbhix.App\Entity\Marks' shared service.
     *
     * @return \App\Entity\Marks
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._ERbhix": it references class "App\\Entity\\Marks" but no such service exists.');
    }
}
