<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParents2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cJMmeiO.App\Entity\Parents' shared service.
     *
     * @return \App\Entity\Parents
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cJMmeiO": it references class "App\\Entity\\Parents" but no such service exists.');
    }
}
