<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubject2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wioxKy0.App\Entity\Subject' shared service.
     *
     * @return \App\Entity\Subject
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wioxKy0": it references class "App\\Entity\\Subject" but no such service exists.');
    }
}
