<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSchoolClass2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.REoQTBa.App\Entity\SchoolClass' shared service.
     *
     * @return \App\Entity\SchoolClass
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.REoQTBa": it references class "App\\Entity\\SchoolClass" but no such service exists.');
    }
}
