<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeTable2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.p.onzoo.App\Entity\TimeTable' shared service.
     *
     * @return \App\Entity\TimeTable
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.p.onzoo": it references class "App\\Entity\\TimeTable" but no such service exists.');
    }
}
