<?php

namespace ContainerN2TGcof;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeacherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5T3lB6g.App\Entity\Teacher' shared service.
     *
     * @return \App\Entity\Teacher
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5T3lB6g": it references class "App\\Entity\\Teacher" but no such service exists.');
    }
}
