<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WmL5zmYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wmL5zmY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wmL5zmY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'timeTable' => ['privates', '.errored..service_locator.wmL5zmY.App\\Entity\\TimeTable', NULL, 'Cannot autowire service ".service_locator.wmL5zmY": it references class "App\\Entity\\TimeTable" but no such service exists.'],
        ], [
            'timeTable' => 'App\\Entity\\TimeTable',
        ]);
    }
}
