<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P_OnzooService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p.onzoo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p.onzoo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'teacherRepository' => ['privates', 'App\\Repository\\TeacherRepository', 'getTeacherRepositoryService', true],
            'timeTable' => ['privates', '.errored..service_locator.p.onzoo.App\\Entity\\TimeTable', NULL, 'Cannot autowire service ".service_locator.p.onzoo": it references class "App\\Entity\\TimeTable" but no such service exists.'],
            'timeTableRepository' => ['privates', 'App\\Repository\\TimeTableRepository', 'getTimeTableRepositoryService', true],
        ], [
            'entityManager' => '?',
            'teacherRepository' => 'App\\Repository\\TeacherRepository',
            'timeTable' => 'App\\Entity\\TimeTable',
            'timeTableRepository' => 'App\\Repository\\TimeTableRepository',
        ]);
    }
}
