<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0BC9czQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0BC9czQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0BC9czQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'student' => ['privates', '.errored..service_locator.0BC9czQ.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.0BC9czQ": it references class "App\\Entity\\Student" but no such service exists.'],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'mailer' => '?',
            'student' => 'App\\Entity\\Student',
            'twig' => '?',
        ]);
    }
}
