<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3Az9MIUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3Az9MIU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3Az9MIU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'divisionRepository' => ['privates', 'App\\Repository\\DivisionRepository', 'getDivisionRepositoryService', true],
        ], [
            'divisionRepository' => 'App\\Repository\\DivisionRepository',
        ]);
    }
}
