<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7JPgPqBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7JPgPqB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7JPgPqB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'division' => ['privates', '.errored..service_locator.7JPgPqB.App\\Entity\\Division', NULL, 'Cannot autowire service ".service_locator.7JPgPqB": it references class "App\\Entity\\Division" but no such service exists.'],
        ], [
            'division' => 'App\\Entity\\Division',
        ]);
    }
}
