<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1jaqo2tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1jaqo2t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1jaqo2t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'schoolClassRepository' => ['privates', 'App\\Repository\\SchoolClassRepository', 'getSchoolClassRepositoryService', true],
        ], [
            'schoolClassRepository' => 'App\\Repository\\SchoolClassRepository',
        ]);
    }
}
