<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CalGGjSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CalGGjS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CalGGjS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'schoolClass' => ['privates', '.errored..service_locator.CalGGjS.App\\Entity\\SchoolClass', NULL, 'Cannot autowire service ".service_locator.CalGGjS": it references class "App\\Entity\\SchoolClass" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'schoolClass' => 'App\\Entity\\SchoolClass',
        ]);
    }
}
