<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IkvzmsGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IkvzmsG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IkvzmsG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'division' => ['privates', '.errored..service_locator.IkvzmsG.App\\Entity\\Division', NULL, 'Cannot autowire service ".service_locator.IkvzmsG": it references class "App\\Entity\\Division" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'division' => 'App\\Entity\\Division',
            'entityManager' => '?',
        ]);
    }
}
