<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParentsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ParentsController' shared autowired service.
     *
     * @return \App\Controller\ParentsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ParentsController.php';

        $container->services['App\\Controller\\ParentsController'] = $instance = new \App\Controller\ParentsController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ParentsController', $container));

        return $instance;
    }
}
