<?php

namespace ContainerO78Zzjz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeTableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0NZLWBi.App\Entity\TimeTable' shared service.
     *
     * @return \App\Entity\TimeTable
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0NZLWBi": it references class "App\\Entity\\TimeTable" but no such service exists.');
    }
}
