controllers:
    resource: ../src/Controller/
    type: attribute
login:
    path: /login
    controller: App\Controller\SecurityController::login

registration:
    path: /register
    controller: App\Controller\SecurityController::register