<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN2TGcof\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN2TGcof/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN2TGcof.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN2TGcof\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN2TGcof\App_KernelDevDebugContainer([
    'container.build_hash' => 'N2TGcof',
    'container.build_id' => 'c05a4558',
    'container.build_time' => 1700545674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN2TGcof');
